# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DefiPrime.com
#email: youremailaddress@gmail.com
description: List of the best Decentralized Finance Products
#baseurl: "https://defiprime.com" # the subpath of your site, e.g. /blog
url: "https://defiprime.com" # the base hostname & protocol for your site

# Logo settings
logo-image-url: favicon.png
#font-awesome-icon-logo: fas fa-dice-d20

toc:
  min_level: 1 # default: 1
  max_level: 2 # default: 6

pagination:
  enabled: true
  per_page: 16
  permalink: '/page/:num/'
  title: 'DeFi blog - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Build settings
markdown: kramdown
# Layout settings
home-link-in-menu: no
plugins:
  - jekyll-random
include: ['.htaccess']
collections_dir: collections
collections:
  lending:
    output: true
    permalink: /product/:name
    section_url: /decentralized-lending
  derivatives:
    output: true
    permalink: /product/:name
    section_url: /derivatives
  analytics:
    output: true
    permalink: /product/:name
    section_url: /defi-analytics
  assets-management-tools:
    output: true
    permalink: /product/:name
    section_url: /assets-management-tools
  exchanges:
    output: true
    permalink: /product/:name
    section_url: /exchanges
  infrastructure:
    output: true
    permalink: /product/:name
    section_url: /infrastructure
  insurance:
    output: true
    permalink: /product/:name
    section_url: /insurance
  assets-tokenization:
    output: true
    permalink: /product/:name
    section_url: /assets-tokenization
  kyc_identity:
    output: true
    permalink: /product/:name
    section_url: /decentralized_kyc_identity
  marketplaces:
    output: true
    permalink: /product/:name
    section_url: /decentralized_marketplaces
  prediction_markets:
    output: true
    permalink: /product/:name
    section_url: /prediction-markets
  stablecoins:
    output: true
    permalink: /product/:name
    section_url: /stablecoins
  margin-trading:
    output: true
    permalink: /product/:name
    section_url: /margin-trading
  events:
  payments:
    output: true
    permalink: /product/:name
    section_url: /payments
  staking:
    output: true
    permalink: /product/:name
    section_url: /staking
  dao:
    output: true
    permalink: /product/:name
    section_url: /dao
  alternative-savings:
    output: true
    permalink: /product/:name
    section_url: /alternative-savings

defaults:
  -
    values:
      layout: "product"
exclude:
    - .jekyll-cache
    - node_modules
    - README.md
    - CONTRIBUTING.md
keep_files: [images, admin]
sass:
    style: compressed

algolia:
  application_id: U1P9PKRFOS
  index_name: defiprime
  search_only_api_key: 471c4ea8d6a8d6cfce0e09c05807db0e
  #everything in md or html
  files_to_exclude:
    - admin/
    - images/
    - 404.md
    - about.md
    - defi_rates.md
    - blog.md
    - bitcoin.md
    - defi_rates.md
    - defi-events.md
    - eos.md
    - ethereum.md
    - placeholder.md
    - .github/

lazy_load_image:
  src_attr_name: data-src # [required] You need to specify the attributes to be saved for lazy loading
  #preload_image: /path/to/image # [optional] you can add a data uri or loading image as fallback src
  class_attr_values: # [optional] if you want to add custom class value, please add values
    - lazyload
  # ignore_selectors: # [optional] if you want to ignore applying lazy load image, please add selector (css or xpath)
  #   - ".ignore-lazy-image-load"
  #   - "/*[@class='ignore-lazy-image-load']"
  # additional_attrs: # [optional] if you want to add attributes, please add key value
  #   "data-size": auto
